# Generated by Django 4.1.7 on 2023-04-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_apicall_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicall',
            name='user',
        ),
    ]
