# Generated by Django 4.1.7 on 2023-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_vacancylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='count',
            field=models.IntegerField(default=5, verbose_name='Количество вакансий'),
        ),
    ]
