# Generated by Django 4.1.7 on 2023-04-21 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_apicall_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacancyList',
            new_name='HHruVacancyList',
        ),
        migrations.CreateModel(
            name='SuperjobVacancyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=50, verbose_name='Вакансия')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('data', models.TextField(verbose_name='Данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
