# Generated by Django 4.1.7 on 2023-04-23 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_zarplataruvacancylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhruvacancylist',
            name='call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.apicall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superjobvacancylist',
            name='call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.apicall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zarplataruvacancylist',
            name='call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.apicall'),
            preserve_default=False,
        ),
    ]
