# Generated by Django 4.1.7 on 2023-04-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
