# Generated by Django 4.1.7 on 2023-04-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_hhruvacancylist_jdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hhruvacancylist',
            name='jdata',
            field=models.JSONField(default=dict, verbose_name='JSON'),
        ),
    ]
