# Generated by Django 4.1.7 on 2023-04-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_hhruvacancylist_jdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hhruvacancylist',
            name='jdata',
        ),
        migrations.AlterField(
            model_name='hhruvacancylist',
            name='data',
            field=models.JSONField(default=dict, verbose_name='JSON'),
        ),
        migrations.AlterField(
            model_name='superjobvacancylist',
            name='data',
            field=models.JSONField(default=dict, verbose_name='JSON'),
        ),
        migrations.AlterField(
            model_name='zarplataruvacancylist',
            name='data',
            field=models.JSONField(default=dict, verbose_name='JSON'),
        ),
    ]
